// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM3e-uNHrTHCcs4BSeHr1CzmebO-uKyUw',
    appId: '1:39599986104:web:4d73c426643a2f2471eb4d',
    messagingSenderId: '39599986104',
    projectId: 'demoapp-89cbe',
    authDomain: 'demoapp-89cbe.firebaseapp.com',
    storageBucket: 'demoapp-89cbe.firebasestorage.app',
    measurementId: 'G-M95FNBHPNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHwXvP329vD8zcjREJAmnfddqLQe9ujgc',
    appId: '1:39599986104:android:1c0e9ea6450108fe71eb4d',
    messagingSenderId: '39599986104',
    projectId: 'demoapp-89cbe',
    storageBucket: 'demoapp-89cbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG4f0U3Jq07brF0UcF0MNKDyfHYYe61Yc',
    appId: '1:39599986104:ios:3f7729d413907bda71eb4d',
    messagingSenderId: '39599986104',
    projectId: 'demoapp-89cbe',
    storageBucket: 'demoapp-89cbe.firebasestorage.app',
    iosBundleId: 'com.tozakidis.demoApp',
  );
}
